### PR TITLE
More thoughtful completion

### PR DESCRIPTION
**Pull request by kdm9**
A variety of improvements to bash_kernel's completion, all of which try to more semantically match what the user (read: @kdm9) expects when completing from a given position. In particular:

- not completing command names while in something that looks like a path (e.g. `./path/ap<tab>` shouldn't complete the command named `apt`, only the path named `./path/apple.txt`).
- Splitting completion prompts at `=` and `"`, so that one can e.g. complete the path in `variable="./path<tab>"`.

As with all code that tries to be smart, this will likely have a few undesirable corner cases. Please report any issues you encounter!

Making this in a PR so @takluyver has a chance to review/veto it before it it hits `main`. 

**Dear users: if you want to test this now, please install from my dev branch that contains this and the other concurrent PR:**

```
pip uninstall bash_kernel
pip install git+https://github.com/takluyver/bash_kernel.git@kdm9dev
# if you didn't already do this in your conda env/venv/user install, you need to install the kernelspec too:
#python3 -m bash_kernel.install
```

### CODE REVIEW

**Comment by AstrobioMike** [comment]
Heya, folks,

Thanks for your effort on this, @kdm9! I'm trying to test it out, but having a snag. 

I'm doing conda installs of jupyterlab, and after initial setup and activate, then pip install of your dev branch, it seems the kernel isn't yet connected with the notebook. Meaning when I try to find it in the drop-down menu, its option doesn't show up. 

I'm starting to look into how to fix this, but thought i'd ask here in case someone knows right away and/or it helps others trying this out. Do you know how to point/connect jupyter lab to additional kernals installed via pip?

In case it helps/matters, here's what i'm doing so far:

```
mamba create -n jupyter-lab-test -c conda-forge jupyterlab=3.6.0 coreutils=9.1
conda activate jupyter-lab-test

# pip install git+https://github.com/takluyver/bash_kernel.git@kdm9dev

python -m pip install git+https://github.com/takluyver/bash_kernel.git@kdm9dev # tried both just bc, wasn't the problem though
```

thanks for any help!

**Comment by kdm9** [comment]
@AstrobioMike did you do `python3 -m bash_kernel.install` in your new conda env?

**Comment by AstrobioMike** [comment]
i just found that, so lazy of me to have posted here first, haha, thank you!

**Comment by kdm9** [comment]
No probs, I forgot to put it in the instructions above. Please let me know what you think of tab completion now, and if you spot no issues I'll merge this PR (and the associated one fixing conda envs).

**Comment by AstrobioMike** [comment]
Hmm, it still seems to be listing other things for me, and actually is missing the relative path completions in my try right now (unless prefixed with `./`). 

Here's what it looks like for me with the 0.9.0 bash kernel:
image
Where ideally we'd just see "example.txt" and "experiment" show up

Here's what it looks like for me with this dev one:
image
Where now "example.txt" and "experiment" are missing. Did you intend for the relative path options to be gone if not prefixed by `./`?

Reading your summary for the changes you integrated, namely:

> not completing command names while in something that looks like a path (e.g. ./path/ap<tab> shouldn't complete the command named apt, only the path named ./path/apple.txt).

I see this was maybe more focused on completions suggested in a path-like string, but that seems to be already working for me in the base 0.9.0 version, at least in this use-case:
image

And also working the same with the dev install:
image

Meaning, neither of them are adding in programs/commands if a `./` prefixes the thing we're trying to complete. 

I'm not familiar yet with how to setup in such a way i could try changes and re-install my modified files to see how things are actually working in a notebook (though i am happy to figure that out if you'd rather me actually try to help instead of just asking for things :)), but do you think there's a course we could take instead of saying "if it starts with `/`, don't auto-complete possible commands/programs" we say "if it's not the first argument, don't auto-complete possible commands/programs", and instead just relative path items would populate as options (or absolute paths if starting with `/` or `~/`)?

(For quick context of where i'm coming from, i'm trying out putting my unix intro materials into notebooks, and tab-completion not working as expected so far is a sad situation when thinking of that being one of the parts new-comers are so happy to learn about :))

**Comment by kdm9** [comment]
Thanks for testing!!


> Hmm, it still seems to be listing other things for me, and actually is missing the relative path completions in my try right now (unless prefixed with ./).

Hmm, odd, I thought I'd fixed that...

> Here's what it looks like for me with the 0.9.0 bash kernel:
>Where ideally we'd just see "example.txt" and "experiment" show up

So this is very odd, as I see this and the next example the other way around for me. No chance you mixed them up? (beware: they'll both report version 0.9.0 as I didn't bump the version which was a bit daft in retrospect)

> Here's what it looks like for me with this dev one:
> Where now "example.txt" and "experiment" are missing. Did you intend for the relative path options to be gone if not prefixed by ./?

That's how its supposed to happen a the start of the cell:  complete commands unless given something that looks like a path, but not after ls. Maybe I've broken the "at the start" detection...


> Reading your summary for the changes you integrated, namely:

>>    not completing command names while in something that looks like a path (e.g. ./path/ap shouldn't complete the command named apt, only the path named ./path/apple.txt).

> I see this was maybe more focused on completions suggested in a path-like string, but that seems to be already working for me in the base 0.9.0 version, at least in this use-case:
> And also working the same with the dev install:



> Meaning, neither of them are adding in programs/commands if a ./ prefixes the thing we're trying to complete.

Which is desired, right? 



> I'm not familiar yet with how to setup in such a way i could try changes and re-install my modified files to see how things are actually working in a notebook (though i am happy to figure that out if you'd rather me actually try to help instead of just asking for things :)), but do you think there's a course we could take instead of saying "if it starts with /, don't auto-complete possible commands/programs" we say "if it's not the first argument, don't auto-complete possible commands/programs", and instead just relative path items would populate as options (or absolute paths if starting with / or ~/)?

That is what I tried to write originally, and I abandoned it for a reason that I can't quite remember to be honest (perhaps not wanting to break cases where you do e.g. `ls $(cat ./file)` or similar). Perhaps I should just make that the rule, which will be annoyingly incorrect in 1% of cases rather than annoying correct in 99% of cases.

> (For quick context of where i'm coming from, i'm trying out putting my unix intro materials into notebooks, and tab-completion not working as expected so far is a sad situation when thinking of that being one of the parts new-comers are so happy to learn about :))

Totally agree!!

**Comment by AstrobioMike** [comment]
> > Here's what it looks like for me with the 0.9.0 bash kernel:
> > Where ideally we'd just see "example.txt" and "experiment" show up

> So this is very odd, as I see this and the next example the other way around for me. No chance you mixed them up?

So i just tested both from scratch again, labeled the browser tabs as i launched them, and am doing everything in my power to make sure i'm not mixing them up, and as far as i can tell, i'm not – but it certainly wouldn't be the first time that I'm just doing something stupid somewhere, haha. But for me i got the same result, wherein `pip install git+https://github.com/takluyver/bash_kernel.git@kdm9dev` seems to be putting in one where the relative path file and directory are missing following `ls ex` \<tab\>


> > Meaning, neither of them are adding in programs/commands if a ./ prefixes the thing we're trying to complete.

> Which is desired, right?

100%! i was just trying to wrap my head around what your first bullet-point summary was addressing, as i thought it was that type of situation, but i wasn't seeing that being a problem in the base live 0.9.0 version. Is there are more complicated situation that you were referring to as the pull-request addressing with regard to "_not completing command names while in something that looks like a path (e.g. ./path/ap shouldn't complete the command named apt, only the path named ./path/apple.txt)"_?

> That is what I tried to write originally, and I abandoned it for a reason that I can't quite remember to be honest (perhaps not wanting to break cases where you do e.g. ls $(cat ./file) or similar). Perhaps I should just make that the rule, which will be annoyingly incorrect in 1% of cases rather than annoying correct in 99% of cases.

Ah i see... at the moment yea i am feeling it'd be better to \*not be able to tab-complete a command in parentheses like that if that's the trade-off. But maybe that's because i'm in the education mindset for these and not for the programming mindset. 

Also, quick question if i start trying things before this is wrapped up, i see the bettercompletion branch (where this PR initially started from) kernel.py file is different than the kdm9dev branch kernel.py file. Since you have us installing from the kdm9dev branch, i would want to work off of what's in that one if i did anything, right? (just to be sure)

thanks again for your efforts on this thus far!

**Comment by kdm9** [comment]
@AstrobioMike I'll implement what you suggest tomorrow, then merge it all into the dev branch then let you know it's ready to test.

**Comment by kdm9** [comment]
Note to self: this is broken in cases like `command>fil<TAB>` as the python code shell call includes the redirection and thus completions will be written to `fil`.

**Pull request merged**
